### ISSUE TITLE
Exception in thread "main" scala.MatchError: UnknownClassSpec (of class io.kaitai.struct.format.UnknownClassSpec$)

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_tests#15]
I'm trying to build/use master of the tests myself and run into the following issue when executing compilation for Java:

> compiling formats\multiple_use.ksy for java...
> ... => compiled/src/io/kaitai/struct/testformats/MultipleUse.java
> compiling formats\nav_parent.ksy for java...
> ... => compiled/src/io/kaitai/struct/testformats/NavParent.java
> compiling formats\nav_parent_switch.ksy for java...
> ... => compiled/src/io/kaitai/struct/testformats/NavParentSwitch.java
> Exception in thread "main" scala.MatchError: UnknownClassSpec (of class io.kaitai.struct.format.UnknownClassSpec$)
>         at io.kaitai.struct.ClassTypeProvider.makeUserType(ClassTypeProvider.scala:51)
>         at io.kaitai.struct.ClassTypeProvider.determineType(ClassTypeProvider.scala:24)
>         at io.kaitai.struct.ClassTypeProvider.determineType(ClassTypeProvider.scala:16)
>         at io.kaitai.struct.translators.BaseTranslator.detectType(BaseTranslator.scala:228)
>         at io.kaitai.struct.translators.BaseTranslator.detectType(BaseTranslator.scala:290)
>         at io.kaitai.struct.translators.BaseTranslator.translate(BaseTranslator.scala:34)
>         at io.kaitai.struct.languages.components.ObjectOrientedLanguage$class.expression(ObjectOrientedLanguage.scala:9)
>         at io.kaitai.struct.languages.JavaCompiler.expression(JavaCompiler.scala:11)
>         at io.kaitai.struct.languages.JavaCompiler.condIfHeader(JavaCompiler.scala:227)
>         at io.kaitai.struct.languages.components.EveryReadIsExpression$class.attrParse(EveryReadIsExpression.scala:23)
>         at io.kaitai.struct.languages.JavaCompiler.attrParse(JavaCompiler.scala:11)
>         at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$3.apply(ClassCompiler.scala:44)
>         at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$3.apply(ClassCompiler.scala:44)
>         at scala.collection.immutable.List.foreach(List.scala:381)
>         at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:44)
>         at io.kaitai.struct.ClassCompiler$$anonfun$compileSubclasses$1.apply(ClassCompiler.scala:86)
>         at io.kaitai.struct.ClassCompiler$$anonfun$compileSubclasses$1.apply(ClassCompiler.scala:86)
>         at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
>         at io.kaitai.struct.ClassCompiler.compileSubclasses(ClassCompiler.scala:86)
>         at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:59)
>         at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:19)
>         at io.kaitai.struct.Main$.compileOne(Main.scala:92)
>         at io.kaitai.struct.Main$.compileOne(Main.scala:88)
>         at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:124)
>         at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:119)
>         at scala.collection.immutable.List.foreach(List.scala:381)
>         at io.kaitai.struct.Main$.main(Main.scala:119)
>         at io.kaitai.struct.Main.main(Main.scala)

I changed `build-formats` to not build all languages, but only Java and some files build fine, until the build stops on the mentioned one. I guess the problem is for `nav_root.ksy` according to the build order.

Any ideas on what might be the problem?

**Comment by GreyCat** [comment]
The problem seems to be with NavParentSwitch test. It's the test that was introduced recently to check [fix for this bug](https://github.com/kaitai-io/kaitai_struct/issues/48).

There are few things here:

* Are you sure that you use latest compiler (i.e. currentf from git)? Generally, if you check out [umbrella project](https://github.com/kaitai-io/kaitai_struct/), you do `./build-compiler && ./build-formats && ./run-all` to build the compiler, compile tests and run them all. That is exactly what [CI is doing automatically](https://github.com/kaitai-io/kaitai_struct/blob/master/.travis.yml#L74-L77) - you can check it in `.travis.yml` file.
* It's generally normal to have some test failing, due to compiler being under development, newer features / bugfixes introduced and they're done only on some target languages, but not the others. Take a look at [our CI](http://kaitai.io/ci) - not everything is up to 100% for every target language, but we're working on it.
* Due to that "something might always fail" paradigma, build generally should not stop on first error. However, this case is somewhat special, as it happens not in the target language compiler, but before that, in a .ksy parser / preprocessor, which is common to all compilers.

**Comment by tschoening** [comment]
Guten Tag Mikhail Yakshin,
am Montag, 21. November 2016 um 19:56 schrieben Sie:

> Are you sure that you use latest compiler (i.e. currentf from git)?

You are right, I was not, but wanted to start with tag 0.5 instead.
Using master the error doesn't occur, so feel free to close the issue.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow
